In [39]:
l1=[1,2,3]
l2=[4,5,6]
l3=l1+l2

In [24]:
import numpy as np

a1=np.array(l1)
a2=np.array(l2)
print(a1+a2)
a1.shape, type(a1), type(l1), a1.nbytes

[5 7 9]


((3,), numpy.ndarray, list, 24)

In [25]:
!pip install numpy

In [41]:
np.zeros((2,3))
np.ones((2,3))
np.linspace(1,10,5)
np.array(l3).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

##  Type casting, boolean masking, fancy indexing

In [60]:
arr=np.array([1.1, 2.3, 5.8, 4.9, 8.6, 12.5, 15.7],dtype='int64')
# arr.astype('int32')
arr

# ev=[
arr[arr%2==0]#even nos boolean masking
ev=[i for i in range(len(arr))]
arr[ev] # fancy indexing

array([ 1,  2,  5,  4,  8, 12, 15])

## Multidimensional Indexing and Axis


In [27]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9],
               [10,11,12]])
#Axis
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

#indexing
print(arr[3,2])
print(arr[0:3,1:3])

arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
 
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

print(np.sum(arr3D, axis=2))
print(arr3D[0])

arr3D[0,1]=0  # changing data along an axis
print(arr3D)


[22 26 30]
[ 6 15 24 33]
12
[[2 3]
 [5 6]
 [8 9]]
(2, 2, 3)
[[ 6 15]
 [24 33]]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 0  0  0]]

 [[ 7  8  9]
  [10 11 12]]]


## Data Types in Numpy

In [26]:
arr=np.array([3,5,7], dtype=np.int32)
arr.astype('int64')
arr.dtype
arr.nbytes #no. of bytes taken by arr in memory

arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex64')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


## Broadcasting

In [28]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  

[11 12 13 14 15]


#### Broadcasting with Arrays of Different Shapes

In [29]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
 
result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


#### How Broadcasting Works
 Dimensions must be compatible: The size of the trailing dimensions of the arrays must be either the same or one of them must be 1. 
 
Stretching arrays: If the shapes are compatible, NumPy stretches the smaller array to match the larger one, element-wise, without copying data.


## Built in Mathematical Functions in NumPy


In [39]:
import numpy as np
arr = np.array([1, 2, 3,7,3, 4,1, 5])

np.mean(arr)
np.var(arr)
np.min(arr)
np.max(arr)
np.sum(arr)
np.prod(arr)
np.median(arr)
np.percentile(arr, 50)  # For the 50th percentile (median)
np.argmin(arr) #Return the index of the minimum value in an array.
np.unique(arr) #Find the unique elements of an array. removes duplicates
np.diff(arr) #Compute the n-th differences of an array
np.cumsum(arr) #Compute the cumulative sum of an array.
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
np.log(arr) # ln ele
np.exp(arr) # e^ele

array([   2.71828183,    7.3890561 ,   20.08553692, 1096.63315843,
         20.08553692,   54.59815003,    2.71828183,  148.4131591 ])